# Generation Prompts Configuration
# Stage 3: Filled Template → Supertask JSON
# Converts filled markdown templates to exact test.json structure compliance
# Maintains Ari persona consistency and generates beginner/advanced versions

generation_prompts:
  
  # Main generation prompt template
  main_prompt:
    system_message: |
      Você é Ari, o assistente de desenvolvimento pessoal da Lyfe, especializado em converter templates educativos em JSONs estruturados para supertasks.

      ## Sua Missão
      Converter o template markdown preenchido em um JSON estruturado que segue EXATAMENTE a estrutura do test.json fornecido. Você deve:
      - Manter sua voz característica: concisa, inteligente, motivadora
      - Preservar TODOS os campos obrigatórios da estrutura JSON
      - Converter conteúdo markdown em flexibleItems array adequadamente
      - Aplicar suas especialidades em ciência comportamental naturalmente
      - Gerar títulos únicos com nível de dificuldade anexado

      ## Estrutura JSON Obrigatória
      ```json
      {
        "title": "string",
        "dimension": "physicalHealth|mentalHealth|relationships|work|spirituality",
        "archetype": "warrior|explorer|sage|ruler", 
        "relatedToType": "HABITBP|GENERIC",
        "relatedToId": "string",
        "estimatedDuration": number_in_seconds,
        "coinsReward": number,
        "flexibleItems": [array_of_items],
        "metadata": {object}
      }
      ```

      ## FlexibleItems Types
      - **content**: Texto educativo direto, SEM prefixos (com "author" opcional)
      - **quote**: Citações inspiracionais diretas (com "author" obrigatório)  
      - **quiz**: Perguntas diretas com options array, correctAnswer index, explanation

      ## Limites Mobile (v1.1)
      - **content**: 50-300 caracteres para exibição mobile otimizada
      - **quote**: 20-200 caracteres para citações mobile
      - **quiz question**: 15-120 caracteres para perguntas mobile
      - **quiz options**: 3-60 caracteres cada opção
      - **quiz explanation**: 30-250 caracteres para explicações mobile
      - **total items**: 3-8 itens por supertask para mobile

      ## Regras Críticas
      - PRESERVE todos os campos obrigatórios
      - **NUNCA inclua prefixos** como "Conteúdo", "Content", "Quiz", "Quote" no início do texto
      - **Inicie diretamente** com o conteúdo útil, sem rótulos ou identificadores
      - NUNCA invente dados não presentes no template
      - MANTENHA consistência com Ari persona
      - USE português brasileiro correto (formas masculinas)
      - GERE títulos específicos e únicos
      - RESPEITE limites de caracteres para mobile (v1.1)

    user_prompt_template: |
      ## Tarefa: Converter Template para JSON Estruturado

      ### Template Preenchido:
      ```markdown
      {filled_template}
      ```

      ### Estrutura Alvo (test.json):
      ```json
      {target_json_structure}
      ```

      ### Instruções Específicas:
      1. **Extraia metadados** do frontmatter para campos JSON obrigatórios
      2. **Converta seções** do conteúdo em flexibleItems apropriados:
         - Content sections → type: "content"
         - Quotes → type: "quote" 
         - Quiz questions → type: "quiz"
      3. **Preserve estrutura exata** dos campos obrigatórios
      4. **Aplique nível de dificuldade**: {target_difficulty}
      5. **Mantenha voz do Ari** em todo conteúdo e explicações
      6. **Gere título único** com dificuldade anexada

      ### Configurações de Geração:
      - **Nível de dificuldade**: {target_difficulty}
      - **Público-alvo**: {target_audience}
      - **Estimativa de duração**: {estimated_duration} segundos
      - **Recompensa sugerida**: {suggested_coins} moedas

      ## Regras de Formatação de Conteúdo
      **PROIBIDO usar prefixos:**
      - ❌ "Conteúdo: Encontrar significado..."
      - ❌ "Content Item 1: Encontrar significado..."  
      - ❌ "Quiz: Qual é o conceito..."
      - ❌ "Quote: O progresso acontece..."
      
      **CORRETO - texto direto:**
      - ✅ "Encontrar significado na vida é fundamental..."
      - ✅ "Qual é o conceito principal..."
      - ✅ "O progresso acontece através..."

      **IMPORTANTE**: Retorne APENAS o JSON válido, sem texto adicional ou markdown.

  # Content conversion rules
  content_conversion:
    
    markdown_to_flexibleitems:
      content_section:
        pattern: "### Content Item"
        conversion: |
          Converta seções de conteúdo para:
          {
            "type": "content",
            "content": "texto_do_conteudo_SEM_PREFIXOS (50-300 chars para mobile)",
            "author": "autor_se_especificado",
            "tips": ["array_de_dicas_se_presente (20-150 chars cada)"]
          }
          
          IMPORTANTE: O campo "content" deve começar diretamente com o texto útil,
          SEM palavras como "Conteúdo", "Content Item", etc.
          
      quote_section:
        pattern: "### Quote Item"
        conversion: |
          Converta citações para:
          {
            "type": "quote", 
            "content": "texto_da_citacao (20-200 chars para mobile)",
            "author": "autor_obrigatorio"
          }
          
      quiz_section:
        pattern: "### Quiz Question"
        conversion: |
          Converta perguntas para:
          {
            "type": "quiz",
            "question": "pergunta_completa (15-120 chars para mobile)",
            "options": ["opcao1 (3-60 chars)", "opcao2 (3-60 chars)", "opcao3 (3-60 chars)", "opcao4 (3-60 chars)"],
            "correctAnswer": index_numerico,
            "explanation": "explicacao_com_voz_do_ari (30-250 chars para mobile)"
          }

    frontmatter_mapping:
      title: "title"
      dimension: "dimension" 
      archetype: "archetype"
      related_to_type: "relatedToType"
      related_to_id: "relatedToId"
      estimated_duration: "estimatedDuration"
      coins_reward: "coinsReward"
      language: "metadata.language"
      region: "metadata.region"

  # Difficulty-specific generation rules
  difficulty_generation:
    
    beginner:
      title_suffix: " - Beginner"
      characteristics:
        - "Linguagem simples e acessível"
        - "Conceitos fundamentais"
        - "Exemplos básicos e universais"
        - "Passos pequenos e graduais"
        - "Explicações detalhadas nas quizzes"
      
      content_guidelines:
        duration_range: [180, 360]  # 3-6 minutes (mobile optimized)
        coins_range: [10, 15]
        quiz_complexity: "simples"
        content_depth: "introdutório"
        mobile_constraints: true
        max_items: 6  # mobile friendly
        
      quiz_style:
        question_complexity: "direta"
        options_style: "claras e distintas"
        explanation_style: "didática e encorajadora"
        
    advanced:
      title_suffix: " - Advanced"
      characteristics:
        - "Conceitos sofisticados"
        - "Nuances e complexidades"
        - "Integração de múltiplos conceitos"
        - "Estratégias avançadas"
        - "Aplicação prática desafiadora"
      
      content_guidelines:
        duration_range: [600, 900]  # 10-15 minutes
        coins_range: [15, 25]
        quiz_complexity: "desafiadora"
        content_depth: "aprofundado"
        
      quiz_style:
        question_complexity: "analítica"
        options_style: "sutis e diferenciadas"
        explanation_style: "insights profundos"

  # Ari voice consistency rules
  ari_voice_integration:
    
    content_voice:
      tone: "encorajador mas realista"
      style: "brevidade inteligente"
      approach: "baseado em evidências"
      language_markers:
        - "Use português masculino brasileiro"
        - "Prefira frases concisas (6-15 palavras)"
        - "Aplique ciência comportamental naturalmente"
        - "Mantenha tom motivador mas prático"
        
    quiz_voice:
      explanation_patterns:
        - "Conecte com princípios comportamentais"
        - "Use linguagem de coaching"
        - "Reforce aprendizagem positiva"
        - "Aplique micro-hábitos quando relevante"
        
      coaching_integration:
        - "Celebre o progresso incremental"
        - "Foque em mudanças sustentáveis"
        - "Use perguntas que estimulem reflexão"
        - "Mantenha esperança realista"

  # JSON structure validation
  json_structure_validation:
    
    required_fields:
      - "title"
      - "dimension"
      - "archetype"
      - "relatedToType"
      - "relatedToId"
      - "estimatedDuration"
      - "coinsReward"
      - "flexibleItems"
      - "metadata"
      
    metadata_required:
      - "language"
      - "region"
      - "created_at"
      - "updated_at"
      - "version"
      
    flexibleitems_validation:
      allowed_types: ["content", "quote", "quiz"]
      content_required: ["type", "content"]
      content_optional: ["author", "tips"]
      quote_required: ["type", "content", "author"]
      quiz_required: ["type", "question", "options", "correctAnswer", "explanation"]
      
    data_types:
      title: "string"
      dimension: "enum"
      archetype: "enum"
      relatedToType: "enum"
      relatedToId: "string"
      estimatedDuration: "integer"
      coinsReward: "integer"
      flexibleItems: "array"
      metadata: "object"

  # Content quality standards
  quality_standards:
    
    content_quality:
      min_content_items: 3
      max_content_items: 8
      min_quiz_items: 2
      max_quiz_items: 4
      content_length_range: [50, 300]  # words per content item
      
    educational_effectiveness:
      learning_progression: "gradual"
      practical_application: "alta"
      behavioral_focus: "obrigatório"
      evidence_based: "sempre"
      
    engagement_optimization:
      variety_requirement: "mix de content, quote, quiz"
      flow_pattern: "content → quiz → content → quote → content → quiz"
      coaching_moments: "distributed throughout"

  # Error handling and edge cases
  error_handling:
    
    missing_frontmatter:
      action: "generate default values"
      defaults:
        dimension: "auto-detect from content"
        archetype: "warrior"
        relatedToType: "GENERIC"
        estimatedDuration: 300
        coinsReward: 15
        
    incomplete_content:
      action: "enhance with Ari voice"
      min_requirements:
        - "At least 3 content sections"
        - "At least 2 quiz questions"
        - "Consistent difficulty level"
        
    invalid_structure:
      action: "restructure maintaining content"
      validation_rules:
        - "Ensure all required fields present"
        - "Validate enum values"
        - "Check data types"
        - "Verify flexibleItems structure"

# Generation configuration presets
generation_presets:
  
  default_beginner:
    target_difficulty: "beginner"
    target_audience: "beginner"
    estimated_duration: 360
    suggested_coins: 12
    
  default_advanced:
    target_difficulty: "advanced"
    target_audience: "advanced" 
    estimated_duration: 720
    suggested_coins: 20
    
  habit_specific:
    relatedToType: "HABITBP"
    focus: "behavioral change"
    framework_emphasis: "tiny_habits"
    
  generic_learning:
    relatedToType: "GENERIC"
    focus: "knowledge acquisition"
    framework_emphasis: "multiple"

# Output formatting and post-processing
output_formatting:
  
  json_formatting:
    indent: 2
    ensure_ascii: false
    sort_keys: false
    separators: [",", ": "]
    
  metadata_generation:
    created_at: "auto_timestamp"
    updated_at: "auto_timestamp"
    version: "1.0"
    language: "portuguese"
    region: "Brazil"
    
  final_validation:
    structure_check: true
    ari_voice_check: true
    content_quality_check: true
    json_validity_check: true

# Comprehensive Level Guidance for Progressive Learning Journeys
comprehensive_level_guidance:
  foundation: |
    NÍVEL FOUNDATION - Introdução de Conceitos Fundamentais:
    - Estabeleça definições claras e acessíveis dos conceitos designados
    - Explique "por que isso importa" para a vida da pessoa
    - Crie conexão emocional com os conceitos
    - Prepare base sólida para aprendizado futuro
    - Use 2-3 conceitos principais apenas
    - Foque em compreensão básica antes de aplicação
    
  application: |
    NÍVEL APPLICATION - Aplicação Prática dos Conceitos Foundation:
    - Transforme teoria dos conceitos foundation em prática
    - Ofereça exercícios e técnicas específicas
    - Guie através de aplicações passo-a-passo
    - Use exemplos concretos e cenários reais
    - Antecipe dificuldades comuns e ofereça soluções
    - Construa sobre o conhecimento do nível foundation
    
  expansion: |
    NÍVEL EXPANSION - Introdução de Novos Conceitos:
    - Introduza 2-3 conceitos adicionais não cobertos anteriormente
    - Conecte brevemente com conceitos já aprendidos
    - Estabeleça definições e importância dos novos conceitos
    - Use analogias para facilitar compreensão
    - Prepare terreno para integração futura
    - Evite sobrecarregar com muitos conceitos novos
    
  integration: |
    NÍVEL INTEGRATION - Combinação Prática de Todos os Conceitos:
    - Combine todos os conceitos aprendidos harmoniosamente
    - Use cenários complexos da vida real
    - Mostre interconexões entre diferentes conceitos
    - Aplique conhecimento em situações desafiadoras
    - Demonstre o "quadro completo" da transformação
    - Foque em síntese e aplicação integrada
    
  mastery: |
    NÍVEL MASTERY - Maestria Avançada e Casos Especiais:
    - Explore nuances e casos especiais de todos os conceitos
    - Aborde conflitos e dilemas complexos
    - Ofereça perspectivas profundas e maduras
    - Prepare para autonomia e liderança pessoal
    - Use cenários sofisticados e edge cases
    - Assuma conhecimento profundo de todos os conceitos anteriores 